// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getScanCredentials = `-- name: GetScanCredentials :one
SELECT cred.auth_mode, cred.enc_headers
FROM scans sc
JOIN scan_credentials cred ON cred.site_id = sc.site_id
WHERE sc.id = $1
`

type GetScanCredentialsRow struct {
	AuthMode   string `json:"auth_mode"`
	EncHeaders []byte `json:"enc_headers"`
}

// worker が scan_id から当該 site の暗号化認証情報をロードする（復号して注入・ADR-0003）。
// 認証情報が未設定の scan は ErrNoRows として返り、未認証スキャンとして扱う。
func (q *Queries) GetScanCredentials(ctx context.Context, id pgtype.UUID) (GetScanCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getScanCredentials, id)
	var i GetScanCredentialsRow
	err := row.Scan(&i.AuthMode, &i.EncHeaders)
	return i, err
}
