// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFinding = `-- name: InsertFinding :one
INSERT INTO findings (scan_id, template_id, title, severity, url, cwe, remediation)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, scan_id, template_id, title, severity, url, cwe, remediation, status, created_at
`

type InsertFindingParams struct {
	ScanID      pgtype.UUID `json:"scan_id"`
	TemplateID  string      `json:"template_id"`
	Title       string      `json:"title"`
	Severity    string      `json:"severity"`
	Url         string      `json:"url"`
	Cwe         pgtype.Text `json:"cwe"`
	Remediation pgtype.Text `json:"remediation"`
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, insertFinding,
		arg.ScanID,
		arg.TemplateID,
		arg.Title,
		arg.Severity,
		arg.Url,
		arg.Cwe,
		arg.Remediation,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.TemplateID,
		&i.Title,
		&i.Severity,
		&i.Url,
		&i.Cwe,
		&i.Remediation,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
