// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteScan(ctx context.Context, arg CompleteScanParams) (Scan, error)
	// スキャン再試行（running からの再開）時に、部分保存済みの findings を掃除して
	// 再挿入による重複を防ぐ。スキャン実行直前に呼ぶことで再実行を冪等にする。
	DeleteFindingsByScan(ctx context.Context, scanID pgtype.UUID) error
	FailScan(ctx context.Context, id pgtype.UUID) (Scan, error)
	// 状態遷移ガード: WHERE に現在の status を含め、queued→running→done/failed の
	// ライフサイクルのみを許可する。不正な遷移は 0 行更新となり :one では ErrNoRows を
	// 返すため、呼び出し側で「既に遷移済み／不正遷移」として扱える。
	GetScan(ctx context.Context, id pgtype.UUID) (Scan, error)
	// worker が scan_id からスキャン対象（site）情報をロードする。実スキャン前の
	// defense-in-depth 所有確認（ADR-0004）と、スキャン投入先 URL の取得に用いる。
	GetScanTarget(ctx context.Context, id pgtype.UUID) (GetScanTargetRow, error)
	InsertFinding(ctx context.Context, arg InsertFindingParams) (Finding, error)
	StartScan(ctx context.Context, arg StartScanParams) (Scan, error)
}

var _ Querier = (*Queries)(nil)
