// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteScan(ctx context.Context, arg CompleteScanParams) (Scan, error)
	FailScan(ctx context.Context, id pgtype.UUID) (Scan, error)
	InsertFinding(ctx context.Context, arg InsertFindingParams) (Finding, error)
	// 状態遷移ガード: WHERE に現在の status を含め、queued→running→done/failed の
	// ライフサイクルのみを許可する。不正な遷移は 0 行更新となり :one では ErrNoRows を
	// 返すため、呼び出し側で「既に遷移済み／不正遷移」として扱える。
	StartScan(ctx context.Context, arg StartScanParams) (Scan, error)
}

var _ Querier = (*Queries)(nil)
