// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeScan = `-- name: CompleteScan :one
UPDATE scans
SET status = 'done', finished_at = now(), summary_json = $2
WHERE id = $1
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at
`

type CompleteScanParams struct {
	ID          pgtype.UUID `json:"id"`
	SummaryJson []byte      `json:"summary_json"`
}

func (q *Queries) CompleteScan(ctx context.Context, arg CompleteScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, completeScan, arg.ID, arg.SummaryJson)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
	)
	return i, err
}

const failScan = `-- name: FailScan :one
UPDATE scans
SET status = 'failed', finished_at = now()
WHERE id = $1
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at
`

func (q *Queries) FailScan(ctx context.Context, id pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, failScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
	)
	return i, err
}

const startScan = `-- name: StartScan :one
UPDATE scans
SET status = 'running', started_at = now(), engine_version = $2
WHERE id = $1
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at
`

type StartScanParams struct {
	ID            pgtype.UUID `json:"id"`
	EngineVersion pgtype.Text `json:"engine_version"`
}

func (q *Queries) StartScan(ctx context.Context, arg StartScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, startScan, arg.ID, arg.EngineVersion)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
	)
	return i, err
}
