// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeScan = `-- name: CompleteScan :one
UPDATE scans
SET status = 'done', finished_at = now(), summary_json = $2
WHERE id = $1 AND status = 'running'
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset
`

type CompleteScanParams struct {
	ID          pgtype.UUID `json:"id"`
	SummaryJson []byte      `json:"summary_json"`
}

func (q *Queries) CompleteScan(ctx context.Context, arg CompleteScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, completeScan, arg.ID, arg.SummaryJson)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.Preset,
	)
	return i, err
}

const failScan = `-- name: FailScan :one
UPDATE scans
SET status = 'failed', finished_at = now()
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset
`

func (q *Queries) FailScan(ctx context.Context, id pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, failScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.Preset,
	)
	return i, err
}

const getScan = `-- name: GetScan :one

SELECT id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset FROM scans WHERE id = $1
`

// 状態遷移ガード: WHERE に現在の status を含め、queued→running→done/failed の
// ライフサイクルのみを許可する。不正な遷移は 0 行更新となり :one では ErrNoRows を
// 返すため、呼び出し側で「既に遷移済み／不正遷移」として扱える。
func (q *Queries) GetScan(ctx context.Context, id pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.Preset,
	)
	return i, err
}

const getScanTarget = `-- name: GetScanTarget :one
SELECT
    sc.site_id            AS site_id,
    sc.status             AS status,
    s.base_url            AS base_url,
    s.ownership_verified  AS ownership_verified
FROM scans sc
JOIN sites s ON s.id = sc.site_id
WHERE sc.id = $1
`

type GetScanTargetRow struct {
	SiteID            pgtype.UUID `json:"site_id"`
	Status            string      `json:"status"`
	BaseUrl           string      `json:"base_url"`
	OwnershipVerified bool        `json:"ownership_verified"`
}

// worker が scan_id からスキャン対象（site）情報をロードする。実スキャン前の
// defense-in-depth 所有確認（ADR-0004）と、スキャン投入先 URL の取得に用いる。
func (q *Queries) GetScanTarget(ctx context.Context, id pgtype.UUID) (GetScanTargetRow, error) {
	row := q.db.QueryRow(ctx, getScanTarget, id)
	var i GetScanTargetRow
	err := row.Scan(
		&i.SiteID,
		&i.Status,
		&i.BaseUrl,
		&i.OwnershipVerified,
	)
	return i, err
}

const startScan = `-- name: StartScan :one
UPDATE scans
SET status = 'running', started_at = now(), engine_version = $2
WHERE id = $1 AND status = 'queued'
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset
`

type StartScanParams struct {
	ID            pgtype.UUID `json:"id"`
	EngineVersion pgtype.Text `json:"engine_version"`
}

func (q *Queries) StartScan(ctx context.Context, arg StartScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, startScan, arg.ID, arg.EngineVersion)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.Preset,
	)
	return i, err
}
