// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScanCredentials = `-- name: DeleteScanCredentials :exec
DELETE FROM scan_credentials WHERE site_id = $1
`

func (q *Queries) DeleteScanCredentials(ctx context.Context, siteID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanCredentials, siteID)
	return err
}

const getScanCredentials = `-- name: GetScanCredentials :one
SELECT auth_mode, created_at FROM scan_credentials WHERE site_id = $1
`

type GetScanCredentialsRow struct {
	AuthMode  string             `json:"auth_mode"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// api はステータス表示のみで復号しないため、機微な enc_headers は取得しない。
func (q *Queries) GetScanCredentials(ctx context.Context, siteID pgtype.UUID) (GetScanCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getScanCredentials, siteID)
	var i GetScanCredentialsRow
	err := row.Scan(&i.AuthMode, &i.CreatedAt)
	return i, err
}

const upsertScanCredentials = `-- name: UpsertScanCredentials :exec
INSERT INTO scan_credentials (site_id, auth_mode, enc_headers)
VALUES ($1, 'session', $2)
ON CONFLICT (site_id) DO UPDATE
SET auth_mode = EXCLUDED.auth_mode,
    enc_headers = EXCLUDED.enc_headers
`

type UpsertScanCredentialsParams struct {
	SiteID     pgtype.UUID `json:"site_id"`
	EncHeaders []byte      `json:"enc_headers"`
}

// session 認証情報を site 単位で作成/更新する（ADR-0003）。auth_mode は session 固定。
// 「none」は行を作らず不在で表現するため、本クエリは session のみを扱う。
func (q *Queries) UpsertScanCredentials(ctx context.Context, arg UpsertScanCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertScanCredentials, arg.SiteID, arg.EncHeaders)
	return err
}
