// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFindingsByScan = `-- name: ListFindingsByScan :many
SELECT id, template_id, title, severity, url, cwe, remediation, status
FROM findings
WHERE scan_id = $1
ORDER BY
    CASE severity
        WHEN 'Critical' THEN 0
        WHEN 'High' THEN 1
        WHEN 'Medium' THEN 2
        WHEN 'Low' THEN 3
        ELSE 4
    END,
    created_at ASC
`

type ListFindingsByScanRow struct {
	ID          pgtype.UUID `json:"id"`
	TemplateID  string      `json:"template_id"`
	Title       string      `json:"title"`
	Severity    string      `json:"severity"`
	Url         string      `json:"url"`
	Cwe         pgtype.Text `json:"cwe"`
	Remediation pgtype.Text `json:"remediation"`
	Status      string      `json:"status"`
}

// スキャン結果レポート（明細）用。重大度の重い順（Critical→Info）、同一 severity 内は
// 検出順（created_at 昇順）で返す。severity は DB CHECK で 5 値に固定。
func (q *Queries) ListFindingsByScan(ctx context.Context, scanID pgtype.UUID) ([]ListFindingsByScanRow, error) {
	rows, err := q.db.Query(ctx, listFindingsByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingsByScanRow
	for rows.Next() {
		var i ListFindingsByScanRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Title,
			&i.Severity,
			&i.Url,
			&i.Cwe,
			&i.Remediation,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
