// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Finding struct {
	ID          pgtype.UUID        `json:"id"`
	ScanID      pgtype.UUID        `json:"scan_id"`
	TemplateID  string             `json:"template_id"`
	Title       string             `json:"title"`
	Severity    string             `json:"severity"`
	Url         string             `json:"url"`
	Cwe         pgtype.Text        `json:"cwe"`
	Remediation pgtype.Text        `json:"remediation"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Scan struct {
	ID            pgtype.UUID        `json:"id"`
	SiteID        pgtype.UUID        `json:"site_id"`
	Status        string             `json:"status"`
	EngineVersion pgtype.Text        `json:"engine_version"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	SummaryJson   []byte             `json:"summary_json"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ScanCredential struct {
	ID         pgtype.UUID        `json:"id"`
	SiteID     pgtype.UUID        `json:"site_id"`
	AuthMode   string             `json:"auth_mode"`
	EncHeaders []byte             `json:"enc_headers"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Site struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	BaseUrl           string             `json:"base_url"`
	OwnershipVerified bool               `json:"ownership_verified"`
	VerifyMethod      pgtype.Text        `json:"verify_method"`
	VerifyToken       pgtype.Text        `json:"verify_token"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
