// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	GetSiteByID(ctx context.Context, id pgtype.UUID) (Site, error)
	GetSiteByName(ctx context.Context, name string) (Site, error)
	ListSites(ctx context.Context) ([]Site, error)
	MarkSiteVerified(ctx context.Context, id pgtype.UUID) (Site, error)
}

var _ Querier = (*Queries)(nil)
