// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	DeleteScanCredentials(ctx context.Context, siteID pgtype.UUID) error
	GetScan(ctx context.Context, id pgtype.UUID) (Scan, error)
	// api はステータス表示のみで復号しないため、機微な enc_headers は取得しない。
	GetScanCredentials(ctx context.Context, siteID pgtype.UUID) (GetScanCredentialsRow, error)
	GetSiteByID(ctx context.Context, id pgtype.UUID) (Site, error)
	GetSiteByName(ctx context.Context, name string) (Site, error)
	GetSiteByOrigin(ctx context.Context, origin string) (Site, error)
	// ダッシュボードのスコア時系列用。完了かつ summary_json を持つスキャンのみを
	// 日付昇順（折れ線 左→右）で返す。スコアは呼び出し側（report）で summary から算出する。
	// 並び順は report が点の日時に採用する finished_at（無ければ created_at）と一致させ、
	// バックフィルや順不同挿入でも history の順序と表示日時が食い違わないようにする。
	ListDoneScanSummaries(ctx context.Context, siteID pgtype.UUID) ([]ListDoneScanSummariesRow, error)
	// スキャン結果レポート（明細）用。重大度の重い順（Critical→Info）、同一 severity 内は
	// 検出順（created_at 昇順）で返す。severity は DB CHECK で 5 値に固定。
	ListFindingsByScan(ctx context.Context, scanID pgtype.UUID) ([]ListFindingsByScanRow, error)
	ListScansBySite(ctx context.Context, siteID pgtype.UUID) ([]Scan, error)
	ListSites(ctx context.Context) ([]Site, error)
	MarkSiteVerified(ctx context.Context, id pgtype.UUID) (Site, error)
	// scan の存在確認（findings エンドポイントの 404 判定用・summary_json bytea を引かない軽量確認）。
	ScanExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// session 認証情報を site 単位で作成/更新する（ADR-0003）。auth_mode は session 固定。
	// 「none」は行を作らず不在で表現するため、本クエリは session のみを扱う。
	UpsertScanCredentials(ctx context.Context, arg UpsertScanCredentialsParams) error
}

var _ Querier = (*Queries)(nil)
