// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScan = `-- name: CreateScan :one
INSERT INTO scans (site_id, preset)
VALUES ($1, $2)
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset
`

type CreateScanParams struct {
	SiteID pgtype.UUID `json:"site_id"`
	Preset string      `json:"preset"`
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan, arg.SiteID, arg.Preset)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.Preset,
	)
	return i, err
}

const getScan = `-- name: GetScan :one
SELECT id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset FROM scans WHERE id = $1
`

func (q *Queries) GetScan(ctx context.Context, id pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
		&i.Preset,
	)
	return i, err
}

const listDoneScanSummaries = `-- name: ListDoneScanSummaries :many
SELECT id, created_at, finished_at, summary_json
FROM scans
WHERE site_id = $1 AND status = 'done' AND summary_json IS NOT NULL
ORDER BY COALESCE(finished_at, created_at) ASC
`

type ListDoneScanSummariesRow struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	SummaryJson []byte             `json:"summary_json"`
}

// ダッシュボードのスコア時系列用。完了かつ summary_json を持つスキャンのみを
// 日付昇順（折れ線 左→右）で返す。スコアは呼び出し側（report）で summary から算出する。
// 並び順は report が点の日時に採用する finished_at（無ければ created_at）と一致させ、
// バックフィルや順不同挿入でも history の順序と表示日時が食い違わないようにする。
func (q *Queries) ListDoneScanSummaries(ctx context.Context, siteID pgtype.UUID) ([]ListDoneScanSummariesRow, error) {
	rows, err := q.db.Query(ctx, listDoneScanSummaries, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDoneScanSummariesRow
	for rows.Next() {
		var i ListDoneScanSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.SummaryJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScansBySite = `-- name: ListScansBySite :many
SELECT id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at, preset FROM scans
WHERE site_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListScansBySite(ctx context.Context, siteID pgtype.UUID) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listScansBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Status,
			&i.EngineVersion,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SummaryJson,
			&i.CreatedAt,
			&i.Preset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanExists = `-- name: ScanExists :one
SELECT EXISTS(SELECT 1 FROM scans WHERE id = $1)
`

// scan の存在確認（findings エンドポイントの 404 判定用・summary_json bytea を引かない軽量確認）。
func (q *Queries) ScanExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, scanExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
