// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScan = `-- name: CreateScan :one
INSERT INTO scans (site_id)
VALUES ($1)
RETURNING id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at
`

func (q *Queries) CreateScan(ctx context.Context, siteID pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, createScan, siteID)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
	)
	return i, err
}

const getScan = `-- name: GetScan :one
SELECT id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at FROM scans WHERE id = $1
`

func (q *Queries) GetScan(ctx context.Context, id pgtype.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.EngineVersion,
		&i.StartedAt,
		&i.FinishedAt,
		&i.SummaryJson,
		&i.CreatedAt,
	)
	return i, err
}

const listScansBySite = `-- name: ListScansBySite :many
SELECT id, site_id, status, engine_version, started_at, finished_at, summary_json, created_at FROM scans
WHERE site_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListScansBySite(ctx context.Context, siteID pgtype.UUID) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listScansBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Status,
			&i.EngineVersion,
			&i.StartedAt,
			&i.FinishedAt,
			&i.SummaryJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
