// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (name, base_url, verify_method, verify_token)
VALUES ($1, $2, $3, $4)
RETURNING id, name, base_url, ownership_verified, verify_method, verify_token, created_at
`

type CreateSiteParams struct {
	Name         string      `json:"name"`
	BaseUrl      string      `json:"base_url"`
	VerifyMethod pgtype.Text `json:"verify_method"`
	VerifyToken  pgtype.Text `json:"verify_token"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.Name,
		arg.BaseUrl,
		arg.VerifyMethod,
		arg.VerifyToken,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.OwnershipVerified,
		&i.VerifyMethod,
		&i.VerifyToken,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, name, base_url, ownership_verified, verify_method, verify_token, created_at FROM sites WHERE id = $1
`

func (q *Queries) GetSiteByID(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.OwnershipVerified,
		&i.VerifyMethod,
		&i.VerifyToken,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteByName = `-- name: GetSiteByName :one
SELECT id, name, base_url, ownership_verified, verify_method, verify_token, created_at FROM sites WHERE name = $1
`

func (q *Queries) GetSiteByName(ctx context.Context, name string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteByName, name)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.OwnershipVerified,
		&i.VerifyMethod,
		&i.VerifyToken,
		&i.CreatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, name, base_url, ownership_verified, verify_method, verify_token, created_at FROM sites ORDER BY created_at DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.OwnershipVerified,
			&i.VerifyMethod,
			&i.VerifyToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSiteVerified = `-- name: MarkSiteVerified :one
UPDATE sites
SET ownership_verified = true
WHERE id = $1
RETURNING id, name, base_url, ownership_verified, verify_method, verify_token, created_at
`

func (q *Queries) MarkSiteVerified(ctx context.Context, id pgtype.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, markSiteVerified, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.OwnershipVerified,
		&i.VerifyMethod,
		&i.VerifyToken,
		&i.CreatedAt,
	)
	return i, err
}
