/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * スキャンを開始
         * @description site_id のスキャンを enqueue する（worker が非同期実行）。所有確認前は 403。202 で scan_id/status=queued を返す。preset（light/standard/deep・省略時 standard）を任意で受け付ける。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description スキャン対象サイト */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_handler.startScanRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.startScanResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スキャン状態を取得
         * @description スキャンの status とサマリ（done は score/band/counts、未完了は summary=null）を返す。進捗ポーリング兼用。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scan ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_ymd38_goodast_api_internal_report.ScanState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スキャンの findings 明細を取得
         * @description findings を重大度の重い順（Critical→Info）で返す。クリーン（0件）は空配列、scan 不在は 404。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scan ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.findingsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サイト一覧を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.siteResponse"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * サイトを登録
         * @description サイト名とベース URL を登録。非ローカルは所有確認トークン＋設置ガイドを返す。localhost 等は即 verified。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description サイト登録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_handler.registerSiteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.siteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サイト詳細を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.siteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 認証情報の状態を取得
         * @description auth_mode と configured を返す（生値は含めない）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.credentialStatusResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * 認証情報を設定
         * @description 持ち込みセッション（ヘッダ）をアプリ層で暗号化保存（ADR-0003）。生値はレスポンスに含めない。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 認証ヘッダ */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_handler.setCredentialsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.credentialStatusResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 認証情報を削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * サイトのダッシュボード集計を取得
         * @description 最新スコア＋前回差分＋スコア時系列（done スキャンのみ）。スキャン無し/未知サイトは 200＋latest=null・history=[]。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_ymd38_goodast_api_internal_report.DashboardData"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * サイトの診断履歴を取得
         * @description サイトの過去スキャンを新しい順で返す（全 status）。各エントリは GET /scans/{id} と同形。未知サイトは 200＋scans=[]。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.scanHistoryResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ドメイン所有確認を実行
         * @description 設置済みトークンを検証する。未達（未設置・不一致）は 422。成功で ownership_verified=true。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Site ID (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.siteResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Unprocessable Entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "github_com_ymd38_goodast_api_internal_report.Band": "good" | "caution" | "danger" | "crisis";
        "github_com_ymd38_goodast_api_internal_report.DashboardData": {
            history?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.HistoryEntry"][];
            latest?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.LatestState"];
        };
        "github_com_ymd38_goodast_api_internal_report.Finding": {
            cwe?: string;
            id?: string;
            remediation?: string;
            severity?: string;
            status?: string;
            template_id?: string;
            title?: string;
            url?: string;
        };
        "github_com_ymd38_goodast_api_internal_report.HistoryEntry": {
            band?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.Band"];
            counts?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.SeverityCounts"];
            date?: string;
            scan_id?: string;
            score?: number;
        };
        "github_com_ymd38_goodast_api_internal_report.LatestState": {
            band?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.Band"];
            counts?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.SeverityCounts"];
            date?: string;
            delta?: number;
            label?: string;
            scan_id?: string;
            score?: number;
        };
        "github_com_ymd38_goodast_api_internal_report.ScanState": {
            created_at?: string;
            engine_version?: string;
            finished_at?: string;
            id?: string;
            site_id?: string;
            started_at?: string;
            status?: string;
            summary?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.ScanSummary"];
        };
        "github_com_ymd38_goodast_api_internal_report.ScanSummary": {
            band?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.Band"];
            counts?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.SeverityCounts"];
            label?: string;
            score?: number;
        };
        "github_com_ymd38_goodast_api_internal_report.SeverityCounts": {
            critical?: number;
            high?: number;
            info?: number;
            low?: number;
            medium?: number;
            total?: number;
        };
        "internal_handler.ErrorResponse": {
            /** @example invalid site id */
            error?: string;
        };
        "internal_handler.credentialStatusResponse": {
            auth_mode?: string;
            configured?: boolean;
            created_at?: string;
        };
        "internal_handler.findingsResponse": {
            findings?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.Finding"][];
            scan_id?: string;
        };
        "internal_handler.headerInput": {
            name: string;
            value: string;
        };
        "internal_handler.registerSiteRequest": {
            base_url: string;
            name: string;
            verify_method?: string;
        };
        "internal_handler.scanHistoryResponse": {
            scans?: components["schemas"]["github_com_ymd38_goodast_api_internal_report.ScanState"][];
            site_id?: string;
        };
        "internal_handler.setCredentialsRequest": {
            headers: components["schemas"]["internal_handler.headerInput"][];
        };
        "internal_handler.siteResponse": {
            base_url?: string;
            created_at?: string;
            id?: string;
            name?: string;
            ownership_verified?: boolean;
            verification?: components["schemas"]["internal_handler.verificationGuide"];
            verify_method?: string;
            verify_token?: string;
        };
        "internal_handler.startScanRequest": {
            /** @description 省略可。空なら standard（jobs.ParsePreset）。 */
            preset?: string;
            site_id: string;
        };
        "internal_handler.startScanResponse": {
            preset?: string;
            scan_id?: string;
            status?: string;
        };
        "internal_handler.verificationGuide": {
            dns_record?: string;
            file_content?: string;
            file_path?: string;
            method?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
